services:
  web:
    image: ghcr.io/supercakecrumb/chordik/web:v0.0.7
    restart: always
    environment:
      - API_BASE_URL=/api
      - VITE_API_BASE_URL=https://chordik.vkiel.com
    ports:
      - "127.0.0.1:8081:80"      # localhost only
    networks: [chordik-net]

  api:
    image: ghcr.io/supercakecrumb/chordik/server:v0.0.7
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "127.0.0.1:8080:8080"    # localhost only
    depends_on: [db]
    networks: [chordik-net]
    command: sh -c "/app/migrate && /app/api"

  db:
    image: postgres:15
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: [.env]
    networks: [chordik-net]

networks:
  chordik-net: